defaults: &defaults
  adapter: mysql2
  encoding: utf8
  host: localhost
  pool: 15
  timeout: 5000
  username: "wonder"
  password: "weblabs"

development:
  <<: *defaults
  database: "quadroid_server_development"

test: &test
  <<: *defaults
  database: "quadroid_server_test"

production: &production
  <<: *defaults
  database: "quadroid_server"

staging:
  <<: *production

cucumber:
  <<: *test
