defaults: &defaults
  adapter: mysql2
  encoding: utf8
  host: localhost
  pool: 15
  timeout: 5000
  username: "wonder"
  password: "weblabs"

development:
  <<: *defaults
  database: "bestwert_website_development_2"

test: &test
  <<: *defaults
  database: "bestwert_website_test_2"

production: &production
  <<: *defaults
  database: "bestwert_website"

staging:
  <<: *production

cucumber:
  <<: *test
